set gaSet(dnldMode) 0
set gaSet(pioType)  Usb
set gaSet(DutInitName) "SF-1P.E1.DC.4U2S.2RS.2R.tcl"
set gaSet(DutFullName) "SF-1P/E1/DC/4U2S/2RS/2R"
set gaSet(customer) "general"
set gaSet(safaricom.SWver) "vcpeos_5.0.1.229.5_arm.tar.gz"
set gaSet(general.SWver) "vcpeos_5.4.0.127.28_arm.tar.gz"
set gaSet(downloadUbootAnyWay) "Yes"
set gaSet(UutOpt) "SF1P-4UTP"
set gaSet(general.pcpes) "pcpe-general-5.2"
set gaSet(general.flashImg) "flash-image-1.0.4_2G_.bin"
set gaSet(bootScript) "set_boot_param_etx_general.img"
set gaSet(actGen) "general-5.2"
set gaSet(linux_srvr_ip) "172.18.94.42"
