set gaSet(dnldMode) 0
set gaSet(pioType)  Usb
set gaSet(DutInitName) "ETX-1P_SFC.ACEX.1SFP1UTP.4UTP.L1.tcl"
set gaSet(DutFullName) ""
set gaSet(customer) "general"
set gaSet(safaricom.SWver) "vcpeos_5.0.1.229.5_arm.tar.gz"
set gaSet(general.SWver) "vcpeos_5.4.0.77.20_arm.tar.gz"
set gaSet(downloadUbootAnyWay) "Yes"
set gaSet(UutOpt) "ETX1P"
set gaSet(general.pcpes) "pcpe-general-5.2"
set gaSet(general.flashImg) "flash-image-1.0.4_1G_.bin"
set gaSet(bootScript) "set_boot_param_etx_general.img"
set gaSet(actGen) "general-5.2"
set gaSet(linux_srvr_ip) "172.18.94.42"
